language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
install:
  - pip install -r requirements.txt
  - python -m nltk.downloader stopwords
  - python -m nltk.downloader punkt
  - python -m nltk.downloader averaged_perceptron_tagger
script: python ./src/Backend/test.py