version: '3'

services:
  frontend:
    image: cam-frontend
    ports:
      - 10101:4200
    networks: 
      - cam
  backend:
    image: cam-backend
    ports:
      - 10100:5000
    networks: 
      - cam

networks: 
  cam: