version: '3'

services:
  frontend:
    build: ./src/Frontend
    ports:
      - "10051:4200"
    container_name: cam-frontend
  backend:
    build: ./src/Backend
    ports:
      - "10050:5000"
    container-name: cam-backend