version: '2.3'

networks:
  cam:

services:
  frontend:
    build: ./src/Frontend/camFrontend/
    image: cam-frontend3
    ports:
      - 10105:4200
    networks:
      - cam
  backend:
    build: ./src/Backend/
    image: cam-backend3
    ports:
      - 10104:5000
    networks:
      - cam
    links:
      - mysql:mysql
  mysql:
    container_name: cam_mysql
    restart: always
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'cam_root_pass' # TODO: Change this
      MYSQL_USER: 'camuser'
      MYSQL_PASS: 'campass'
    volumes:
      - /srv/docker/pan-cam3/camsqlvolume:/var/lib/mysql
    networks:
      - cam
volumes:
  /srv/docker/pan-cam3/camsqlvolume: